### PR TITLE
chore:  remove protobuf version exclusion

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by noahdietz** [comment]
@dwsupplee [just introduced this](https://github.com/googleapis/common-protos-php/commit/4bad82f73a10f8ea4e6d078da93406a16c996044). Was it an accident, or...?

**Comment by dwsupplee** [comment]
It was not an accident, builds were failing 😔

**Comment by dwsupplee** [comment]
It seems like the 3.20.0 tag was deleted... so I suppose we are safe to remove this

**Review by dwsupplee — APPROVED** [review]

**Comment by bshaffer** [comment]
Yep! I worked with the protobuf team to remove the tag after we added a safe one!

**Pull request merged**
