### PR TITLE
feat: update routing and extended-operations protos

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Review by noahdietz — APPROVED** [review]

**Review by chingor13 — APPROVED** [review]

**Comment by chingor13** [comment]
Probably want this as a `feat` type?

**Comment by bshaffer** [comment]
> Probably want this as a `feat` type?

Good call. Even though updating Protos seems like a chore :P

**Review by tmatsuo — APPROVED** [review]
Are we sure that release-please refers to the PR title instead of the commit message?

**Comment by bshaffer** [comment]
> Are we sure that release-please refers to the PR title instead of the commit message?

I don't think release-please is involved in our process with this repo yet.

**Pull request merged**
